version: '3.8'

services:
  app-test:
    container_name: descomplica-backend-test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:password123@db-test:5432/alunos-db-test?schema=public
      JWT_SECRET: test-secret-key
      JWT_EXPIRES_IN: 1d
    command: >
      sh -c "
      echo 'ðŸš€ Running E2E tests...' &&
      npx prisma migrate deploy &&
      npm run prisma:generate:test &&
      npm run test:e2e
      "
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  db-test:
    image: postgres:15
    container_name: alunos-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: alunos-db-test
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata_test: